### ISSUE TITLE
Add article images as a background 

### ISSUE THREAD

**Issue by elim322** [lstasiuk/Instanews#3]
https://github.com/lstasiuk/Instanews/blob/c8b4d7a2ede4088909313047bf718d7b45f0646c/build/js/jscript.js#L27

Append image as a background and give a background size of cover and background position center to center align the images on the website.

**Comment by resonantdoghouse** [comment]
I don't think this is fixed yet, or it might be due to the fact that the ./js folder is missing?

What Einer is saying is basically to try using inline style for the outer div e.g. articles and to use a background image there instead of the image tag you are using. 

This in combination with background-size: cover and background-position: center will help to scale and fill the images for each item.
